import telebot
import os
from dotenv import load_dotenv
load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

class TelegramMessenger:
    def __init__(self, bot_token: str, chat_id: str):
        self.bot = telebot.TeleBot(BOT_TOKEN)
        self.chat_id = CHAT_ID

    def send_message(self, msg: str):
        self.bot.send_message(self.chat_id, msg, parse_mode="HTML")

    def send_signal(self, symbol, action, price, time):
        emoji = "🟢 BUY" if action.upper() == "BUY" else "🔴 SELL"

        message = f"""
<b>{emoji} SIGNAL</b>

<b>Symbol:</b> {symbol}
<b>Action:</b> {action}
<b>Entry:</b> {price}
<b>Time:</b> {time}

⚡ <i>Auto-generated by AIEngineX</i>
"""
        self.send_message(message)


